version: '3.8'

services:
  app:
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_DRUPAL_BASE_URL=http://drupal-headless.docksal.ny.gov
      - NEXT_IMAGE_DOMAIN=drupal-headless.docksal.ny.gov
    build:
      context: .
      args:
        NEXT_PUBLIC_DRUPAL_BASE_URL: ${NEXT_PUBLIC_DRUPAL_BASE_URL}
    ports:
      - "3000:3000"
  # web:
  #   build: .
  #   command: npm start
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./web
  #         target: /src/web
  #         ignore:
  #           - node_modules/
  #       - action: rebuild
  #         path: package.json