version: '3.8'

services:
  app:
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_DRUPAL_BASE_URL=http://drupal-headless.docksal.ny.gov
      - NEXT_IMAGE_DOMAIN=drupal-headless.docksal.ny.gov
    build:
      context: .
      args:
        NEXT_PUBLIC_DRUPAL_BASE_URL: ${NEXT_PUBLIC_DRUPAL_BASE_URL}
    ports:
      - "3000:3000"
